# Generated by Django 5.2.8 on 2025-11-15 01:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10001)])),
                ('razon_social', models.CharField(max_length=255)),
                ('mercado', models.CharField(choices=[('ACN', 'ACN - Acciones Nacionales'), ('RVI', 'RVI - Renta Variable Internacional'), ('RVE', 'RVE - Renta Variable Emergente')], max_length=3)),
                ('tipo_sociedad', models.CharField(max_length=100)),
                ('factor_8', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_9', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_10', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_11', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_12', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_13', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_14', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_15', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_16', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_17', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_18', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('factor_19', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comentarios_auditor', models.TextField(blank=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('corredor', 'Corredor'), ('auditor', 'Auditor'), ('administrador', 'Administrador')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
